server:
    port: 8761
eureka:
    instance:
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ip-address}:${server.port}
        hostname: ${spring.cloud.client.ip-address}
    client:
        service-url:
            defaultZone: http://127.0.0.1:8761/eureka
        register-with-eureka: false
    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 5000
        response-cache-update-interval-ms: 3000
