server:
    port: 8763
eureka:
    instance:
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ip-address}:${server.port}
        hostname: ${spring.cloud.client.ip-address}
    client:
        service-url:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    server:
        enable-self-preservation: false
