management:
  metrics:
    web:
      server:
        autoTimeRequests: false
server:
  port: 9009
zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      hosts: http://localhost:9200
      index: zipkin